version: '3.8'

services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
    - COINGECKO_API_KEY= 
    - MONGODB_URL
    - PORT=3000
